### ISSUE TITLE
How to control S11639 bare board

### ISSUE THREAD

**Issue by 9xiaolaji30** [drmcnelson/S11639-01-Linear-CCD-PCB-and-Code#1]
Hello Doctor, I bought a Hamamatsu CMOS (S11639) with only a bare board. Now I need to drive it to output the correct video signal. First, I control the CLK signal and ST signal according to the technical manual, but the output of the video signal is only a few hundred millivolts, and the stronger the light intensity, the smaller the signal. This seems to violate the instructions in the technical manual. Can you show me the ST signal and CLK signal you control? If there is an oscilloscope, the waveform will be better. If not, please tell me how you control the ST signal and CLK signal. Thank you very much! Dear M C Nelson, PhD,

**Comment by drmcnelson** [comment]
Hi,  this is not actually an issue with anything I posted.   You are asking me about the board that you purchased.  Please send me a private note and schematics for what you bought.
